FROM rust:1.66-alpine AS builder

RUN apk add --no-cache g++ zlib zlib-dev 

WORKDIR /app
COPY . /app
RUN cargo build --release --features=hashicorp

FROM alpine
COPY --from=builder /app/target/release/tmkms /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/tmkms"]