name: Build docker image

on:
  push:
    branches:
      - feat/add-vault-support

jobs:
  docker:
    runs-on: ubuntu-latest-l
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.hashicorp
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nibiruchain/tmkms:vault
